// Root layout (HTML structure, metadata).


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

//FONT CONFIGURATION
const geistSans = Geist({  // load sans serif font
  variable: "--font-geist-sans",  // creates css variable
  subsets: ["latin"],
});

const geistMono = Geist_Mono({ //loads monospace fonts
  variable: "--font-geist-mono", //creates css variable
  subsets: ["latin"],
});


//META DATA (SEO) -> controlls page title, Meta description,SEO and browser tab
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// ROOTLAYOUT COMPONENT
export default function RootLayout({
  children, // CONTENT OF EACH ROUTE
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html // HTML STRUCTURE
      lang="en" //accessibility+ SEO(search engine optimisation) ->understands the page language, shows to the correct audience
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`} // h-full → full height ,antialiased → smoother text rendering (Tailwind)
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>// min-h-full → full height layout, flex flex-col → vertical layout (useful for navbar + footer), {children} → renders current route UI
  );
}
